name: Retail App CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login retailacrdev.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Image
      run: |
        docker build -t retailacrdev.azurecr.io/retail-app:v${{ github.run_number }} .

    - name: Push Image
      run: |
        docker push retailacrdev.azurecr.io/retail-app:v${{ github.run_number }}
